# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20181228_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/users', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
