# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181203_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст поcта'),
        ),
    ]
