# Generated by Django 2.1.1 on 2018-12-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181217_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='comments_post',
        ),
    ]
