# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181221_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='send_date',
            new_name='published_date',
        ),
    ]
