# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20190214_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
