# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190219_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
